### ISSUE TITLE
Pause menu is broken

### ISSUE THREAD

**Issue by TheLemon27** [Starmapo/Lullaby-Forever-Fix#1]
the menu when you pause mid-song is broken, the text and arrow don't align with each other, and they both aren't aligned with the box. selecting things works like normal though.

**Comment by TheLemon27** [comment]
oh whoops i read that u wont be fixing it ok fair enough

**Comment by Starmapo** [comment]
Yeah, the source code that was released came with this bug in it, no idea why since it isn't there in the official build.

I might just take another look at it though, not really doing anything else at the moment anyways
