### ISSUE TITLE
Game crash after beating Frostbite

### ISSUE THREAD

**Issue by TheLemon27** [Starmapo/Lullaby-Forever-Fix#2]
So whenever I beat Frostbite now, the game crashes shortly after giving me pokedollars.
It worked just fine yesterday, but it was getting late so I quit in the middle of the week and came back today to find that whenever I beat Frostbite, the game just crashes.
Crash dump if that helps:
`flixel/system/FlxSound.hx (line 591)`
`flixel/system/FlxSound.hx (line 717)`
`flixel/system/FlxSoundGroup.hx (line 52)`
`flixel/system/frontEnds/SoundFrontEnd.hx (line 327)`
`flixel/system/frontEnds/SoundFrontEnd.hx (line 319)`
`flixel/FlxGame.hx (line 618)`
`flixel/FlxGame.hx (line 729)`
`flixel/FlxGame.hx (line 682)`
`flixel/FlxGame.hx (line 556)`
`openfl/events/EventDispatcher.hx (line 402)`
`openfl/display/DisplayObject.hx (line 1399)`
``
`Uncaught Error: Null Object Reference`

(also sorry for giving u so many bug reports)

**Comment by TheLemon27** [comment]
ok so i tried it again and it worked??????? idk whats going on whith this
edit: when i lost Insomnia and tried to retry it, it crashed. I hope you don't mind but i'm gonna open a different issue for it with the crash message.
(once again, sorry for finding so many bugs)

**Comment by Starmapo** [comment]
> edit: when i lost Insomnia and tried to retry it, it crashed.

Was it the same crash dump as before?

**Comment by TheLemon27** [comment]
> > edit: when i lost Insomnia and tried to retry it, it crashed.
> 
> Was it the same crash dump as before?

no, i uploaded the crash dump in the other issue

**Comment by Starmapo** [comment]
I can't seem to reproduce this crash. Were you doing anything out of the ordinary when you got it?

**Comment by TheLemon27** [comment]
> I can't seem to reproduce this crash. Were you doing anything out of the ordinary when you got it?

not to my knowledge, no

**Comment by TheLemon27** [comment]
also worth noting: i havent seen the crash myself ever since this post:

> ok so i tried it again and it worked??????? idk whats going on whith this edit: when i lost Insomnia and tried to retry it, it crashed. I hope you don't mind but i'm gonna open a different issue for it with the crash message. (once again, sorry for finding so many bugs)

**Comment by Starmapo** [comment]
I still can't reproduce it either, so I'll mark this as closed unless it keeps happening to you in the next update.

**Comment by TheLemon27** [comment]
i think you should mark it as "not planned" for now
