### ISSUE TITLE
In Pasta Night, Hypno has no left arrows (NOT A CHART MISTAKE)

### ISSUE THREAD

**Issue by TheLemon27** [Starmapo/Lullaby-Forever-Fix#5]
So... I'm back.
I finally played pasta night, and chose Hypno to play as. and I thought to myself as I was playing "huh, this chart doesn't feel good to play" and I also noticed a striking lack of left arrows on Hypnos' side of the field. I decided to open the chart editor to see if it was a chart issue, and sure enough, in the editor, all the lefts are there and accounted for. just to test, i added some extra lefts to the chart, saved it, and played it and sure enough, nothing happened.
So, Hypnos' left arrows just don't spawn for whatever reason?

**Comment by Starmapo** [comment]
Are you playing on the latest version? Cause I noticed that bug on the original release and I thought I fixed it for the update.

**Comment by TheLemon27** [comment]
No I'm still on the original, I'll try the update now.

**Comment by TheLemon27** [comment]
ok yeah that fixes it sorry

**Comment by TheLemon27** [comment]
ok: something else to note is that the new update fixes the pause menu for some reason (it's not in the patch notes so a assume you didnt mean to fix it)

**Comment by Starmapo** [comment]
Oh yeah, I did forget to mention that. Somehow when I upgraded the libraries to the latest versions, the pause menu was just fixed. I guess I was using the wrong version of HaxeFlixel for the original release.
