### ISSUE TITLE
Launch trouble

### ISSUE THREAD

**Issue by FlameAidi** [Starmapo/Lullaby-Forever-Fix#7]
My friend can't beat first week, and my notebook can't accept Frostbite's shaders too, so I really need this fix. But I don't know how to launch it. I've tried psych engine, Forever engine, even tried to merge Hypno's Lullaby v2 with this fix, but nothing works. Pussy mode still not working, and there is no shader options.

So, how do I install this fix?

**Comment by Starmapo** [comment]
This isn't a "fix" to apply to the game, its a modified version of it. You can download it through the releases page: https://github.com/Starmapo/Lullaby-Forever-Fix/releases

**Comment by FlameAidi** [comment]
Oh, that worked! Thank you so much! That's what I need!
